### ISSUE TITLE
Problem when loading 

### ISSUE THREAD

**Issue by 7AM7** [leftspace89/LSFlatPM#3]
Hello there !

Kindly it's great work  and thank you for sharing code .

I have problem when loading plugin 
```
Downloading Plugin List..
Plugin is up to date [LSP_Aimbot.dll]
Plugin is up to date [LSP_ESP.dll]
Plugin is up to date [LSP_Radar.dll]
Plugin is up to date [LSP_Awareness.dll]
Plugin is up to date [LSP_AdvancedESP.dll]
Loading Plugins..
Search..

Unhandled Exception: Search DONE..
System.IO.FileNotFoundException: Could not load file or assembly 'ESP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at System.UnitySerializationHolder.GetRealObject(StreamingContext context)

   at System.AppDomain.Load(AssemblyName assemblyRef)
   at LSFlatPM.PluginLoader.#=za2eFMJs=(String #=z_BPQvC8=)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at #=q4UVR2rx7ciEHolQXfv9Xh70ffMdqtWiW4uCpdTE3PPI=.#=zZWnklWJ8ybdxhfu$1XMAgFCO0gcknK6VnkVTtQg=(Exception #=zf_dRx4s=)
   at #=q4UVR2rx7ciEHolQXfv9Xh70ffMdqtWiW4uCpdTE3PPI=.#=ziyqJ8O75riQ8mWP$Oq1SE_LLAPN2acZiGMoBVzQ=(Object #=zf_dRx4s=)
   at #=q4UVR2rx7ciEHolQXfv9Xh70ffMdqtWiW4uCpdTE3PPI=.#=zZtY6numGnm$cHVSH18YWjossr1DkA4uDOA==(MethodBase #=zf_dRx4s=, Boolean #=zb$ByG2A=)
   at #=q4UVR2rx7ciEHolQXfv9Xh70ffMdqtWiW4uCpdTE3PPI=.#=zc0QzOYME9Exh6qbeD_9KQyQ=(#=q4UVR2rx7ciEHolQXfv9Xh70ffMdqtWiW4uCpdTE3PPI= #=zf_dRx4s=, #=q8W0d1wmcpg6bJouAXDKB7fVuoMvrKv88UWJPtkzB2PU= #=zb$ByG2A=)
   at #=q4UVR2rx7ciEHolQXfv9Xh70ffMdqtWiW4uCpdTE3PPI=.#=zzI$8R03UZkgL6Za2LbWBMsny2M9wITkyEw==()
   at #=q4UVR2rx7ciEHolQXfv9Xh70ffMdqtWiW4uCpdTE3PPI=.#=zN0mq0KqfvYtsqbqKCw==(Boolean #=zf_dRx4s=)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at #=q4UVR2rx7ciEHolQXfv9Xh70ffMdqtWiW4uCpdTE3PPI=.#=zZWnklWJ8ybdxhfu$1XMAgFCO0gcknK6VnkVTtQg=(Exception #=zf_dRx4s=)
   at #=q4UVR2rx7ciEHolQXfv9Xh70ffMdqtWiW4uCpdTE3PPI=.#=ziyqJ8O75riQ8mWP$Oq1SE_LLAPN2acZiGMoBVzQ=(Object #=zf_dRx4s=)
   at #=q4UVR2rx7ciEHolQXfv9Xh70ffMdqtWiW4uCpdTE3PPI=.#=zAXN$LjR$O2Yv0o7GiaSdC383tjuyQflUdmlnVOz1TqYP()
   at #=q4UVR2rx7ciEHolQXfv9Xh70ffMdqtWiW4uCpdTE3PPI=.#=zp83l90GVns5jiukI_J6nDswFIpjn(Object #=zf_dRx4s=, UInt32 #=zb$ByG2A=)
   at #=q4UVR2rx7ciEHolQXfv9Xh70ffMdqtWiW4uCpdTE3PPI=.#=zN0mq0KqfvYtsqbqKCw==(Boolean #=zf_dRx4s=)
   at #=q4UVR2rx7ciEHolQXfv9Xh70ffMdqtWiW4uCpdTE3PPI=.#=z5h$5XtUg8LxHybW7ShaLDFb55N9VyUw3nVhn4Cc=()
   at #=q4UVR2rx7ciEHolQXfv9Xh70ffMdqtWiW4uCpdTE3PPI=.#=zgUMBaTV$f1K_S2Ay7uqpqppBXoa2K1TeIg==(Object[] #=zf_dRx4s=, Type[] #=zb$ByG2A=, Type[] #=zJ6sQ0eg=, Object[] #=za4zoHgU=)
   at #=q4UVR2rx7ciEHolQXfv9Xh70ffMdqtWiW4uCpdTE3PPI=.#=z2dNxY3MvWxecskzhM1W89O6ErdQqc7GNGw==(Stream #=zf_dRx4s=, String #=zb$ByG2A=, Object[] #=zJ6sQ0eg=, Type[] #=za4zoHgU=, Type[] #=zqdCvbFY=, Object[] #=zwlpJ29g=)
   at #=q4UVR2rx7ciEHolQXfv9Xh70ffMdqtWiW4uCpdTE3PPI=.#=z$GpHnJAbtyiNeeG1L2YZd2UgCrynMee52w==(Stream #=zf_dRx4s=, String #=zb$ByG2A=, Object[] #=zJ6sQ0eg=)
   at #=q4UVR2rx7ciEHolQXfv9Xh70ffMdqtWiW4uCpdTE3PPI=.#=zJp6eKuwJSicBDKUzP9zLShU=(Stream #=zf_dRx4s=, String #=zb$ByG2A=, Object[] #=zJ6sQ0eg=)
   at #=zJvJIs_lW_XwFIhETOg==.#=za2eFMJs=()
   at #=zJvJIs_lW_XwFIhETOg==.#=zcwsPRUk=(String[] #=zeBPNQUM=)
   at #=qfhVU9M_ezxmmi95LOPqxcg8zwE0wOc5GtFstFsb8DvU=.#=zLdrlLnU=(String[] #=zf_dRx4s=)

```

## I renamed the filename to DLSP_ESP and put it in TEMP folder

**Comment by 7AM7** [comment]
## Fixed I didn't change Assembly name
